services:
  - type: web
    name: plant-disease-classifier
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_sklearn:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18